name: Docker Build and Deploy

inputs:
  directory:
    description: 'Directory path'
    required: true
  name:
    description: 'Name of app'
    required: true
  port_map:
    description: 'Port mapping'
    required: true

runs:
  using: "composite"
  steps:
    - name: Stop Existing Container
      shell: bash
      run: docker stop ${{ inputs.name }} || true

    - name: Prune Docker System
      shell: bash
      run: docker system prune -a -f

    - name: Build Docker Image
      shell: bash
      run: |
        docker build \
          --build-arg DIRECTORY=${{ inputs.directory }} \
          -f ${{ inputs.directory }}/Dockerfile \
          -t ${{ inputs.name }} .

    - name: Prune Containers
      shell: bash
      run: docker container prune -f

    - name: Run Docker Container
      shell: bash
      run: |
        docker run -d -i \
          --cpu-shares=4096 \
          --name ${{ inputs.name }} \
          -p ${{ inputs.port_map }} \
          ${{ inputs.name }}

    - name: Prune Docker Images
      shell: bash
      run: docker image prune -f
