name: portfolio-app

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Runner'
        required: true
        default: 'information'
        type: choice
        options:
          - portfolio-app-runner
          - debug
          - warning
          - critical

jobs:
  deploy_fund_portfolio:
    name: portfolio-app
    runs-on:
      # labels: portfolio-app-runner # needs to match ${stackname}-runner
      labels: ${{ inputs.tags }}

    steps:
      - name: dflow-deploy
        uses: ../actions/dflow-deploy
        with:
          directory: "cmd/portfolio/fund"
          system_image: "portfolio_fund_image"
          container_name: "portfolio-fund"
          port_map: "80:80"
