name: portfolio-app

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'information'
        type: choice
        options:
          - information
          - debug
          - warning
          - critical
      tags:
        description: 'Purpose of Run This Workflow?'
        required: true
        type: string

jobs:
  deploy_fund_portfolio:
    name: portfolio-app
    runs-on:
      labels: portfolio-app-runner # needs to match ${stackname}-runner

    steps:
      - name: dflow-deploy
        uses: ../actions/dflow-deploy
        with:
          directory: "cmd/portfolio/fund"
          system_image: "portfolio_fund_image"
          container_name: "portfolio-fund"
          port_map: "80:80"
