name: portfolio-app

on:
  workflow_dispatch:

jobs:
  deploy_fund_portfolio:
    name: portfolio-app
    runs-on:
      labels: portfolio-app-runner # needs to match ${stackname}-runner

    steps:
      - name: dflow-deploy
        uses: ../actions/dflow-deploy
        with:
          directory: "cmd/portfolio/fund"
          system_image: "portfolio_fund_image"
          container_name: "portfolio-fund"
          port_map: "80:80"
