name: portfolio-app

on:
  workflow_dispatch:

jobs:
  dflow:
    name: dflow
    runs-on:
      labels: portfolio-app-runner # needs to match ${stackname}-runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: ls
        run: ls ./.github/actions/dflow-deploy
      - name: dflow-deploy
        uses: "./.github/actions/dflow-deploy"
        with:
          directory: "cmd/portfolio/fund"
          name: ${{ job.name }}
          port_map: "80:80"
