name: dflow

on:
  workflow_dispatch:
    inputs:
      portfolio-app:
        type: boolean
        required: true
        default: false

      other-box:
        type: boolean
        required: true
        default: false

jobs:
  portfolio-app:
    if: inputs.portfolio-app == true
    name: portfolio-app
    runs-on: portfolio-app-runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: dflow-deploy
        uses: "./.github/actions/dflow-deploy"
        with:
          directory: "cmd/portfolio/fund"
          name: $GITHUB_JOB
          port_map: "80:80"

  other-box:
    if: inputs.other-box == true
    name: other-box
    runs-on: other-box-runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: dflow-deploy
        uses: "./.github/actions/dflow-deploy"
        with:
          directory: "cmd/boxes/other"
          name: $GITHUB_JOB
          port_map: "80:80"